### ISSUE TITLE
edit/add is not working

### ISSUE THREAD

**Issue by elig0n** [d3ward/nextntp#11]
In https://d3ward.github.io/nextntp/
The edit/new link button in the main links bar or in the empty folder do nothing.

Tried with:
Firefox 90.0.1 + Incognito
Qutebrowser.2.3.0

**Comment by d3ward** [comment]
Hi , you need to pick a tile and drag into the action you want to do . Can you try that and let me know if issue persist

**Comment by elig0n** [comment]
I dragged the Kiwi Browser tile into the empty folder successfully but could not drag it out of it.
I can right click it and from the popup that opens click on the trash-bin icon or the pen-and-paper icon but they do nothing.
How can I add new tiles with custom URLs ?

**Comment by d3ward** [comment]
Hi , you still face the issue ? 
When you have a tile inside a folder , long click to enable edit mode , now drag the tile to the action , the bottom left one will delete the tile , the center one will bring the tile out of folder and bottom right one will make you edit the tile .
For adding a new tile , click the arrow in bottom right then Add new tile

**Comment by elig0n** [comment]
Works great. But where did the previous cloud background go though? I liked it better.
