### ISSUE TITLE
Issue w/ default bookmark tiles

### ISSUE THREAD

**Issue by Chaprnks** [d3ward/nextntp#21]
I have been following this repo occasionally & would love to switch from the stock NTP. The main issue that I have always had, preventing me from switching; is the default NTP tiles.

Long pressing the folder or bookmark, enables the edit screen. Tapping the delete button doesn't seem to do anything to the bookmark or folder, as they permanently stay.

As a temporary workaround (albeit painfully slow); it may be possible to export the backup to a file, edit the file (removing the bookmark lines), then finally importing the edited backup file.

**Comment by d3ward** [comment]
Hey , after long press you enter the edit mode of tiles . From there you have to drag the tile to the action you want to take . Drag a tile on the trash and will delete it , drag on the pencil and a prompt to edit will be there . Sorry if this wasnt intuitive , i will improve that in future updates

**Comment by Chaprnks** [comment]
What a quick reply, glad to see an active developer; addressing GitHub issues so quickly. Anyways, thank you so much! I guess this could be considered a "user error" & not an actual issue. :satisfied:  I'd suggest adding a note on the README (and/or about tab on the nextntp itself), so others don't encounter the same problem as I did.
