### ISSUE TITLE
News widget not working

### ISSUE THREAD

**Issue by brokoler** [d3ward/nextntp#23]
Hello,

the news widget is not working for me, it's loading endlessly without showing news articles.
I'm using Kiwi Browser 98.0.4758.60 and tried this with your demo page and via installing the extensions (v1.0.4).
I checked that no DNS entries are blocked, which wasn't the case.

Would be great to see a fix for this. Also would be great to choose from different news sources.

Best regards

**Comment by rafagale** [comment]
Same for me kiwiersionkiwi 99.0.4844.66
