### ISSUE TITLE
Can it be made to support links to URL schemas other than http:// and https:// ?

### ISSUE THREAD

**Issue by EricDru** [d3ward/nextntp#26]
Hi
I like 'Next NTP' in Kiwi, but tried something it didn't support.

There are a set of 'internal settings' pages in Kiwi etc, accessed by URLs like
kiwi://about
chrome://about
kiwi://flags

In 'Next NTP', the link gets re-interpreted
kiwi://about
https://kiwi//about
So 'Next NTP' links fail.

If it could be generalised for 
mailto://
nntp://
ftp://
etc

[ URI schemes - Wikipedia ](https://en.wikipedia.org/wiki/List_of_URI_schemes)
[ URI schemes - w3.org ](https://www.w3.org/wiki/UriSchemes)

that would be ideal!

Thanks,
Eric

**Comment by d3ward** [comment]
Thanks for the feedback. This will be one of the main improvements on next update

**Comment by EricDru** [comment]
Kiwi's own 'Modern Homepage' doesn't support 'kiwi://' either, 'Classic' does, sort-of.
(works, but label is 'null')
Trying b2ntp ....
Thanks!

**Comment by EricDru** [comment]
[Off-topic] b2ntp
v.1.0.3 from here errored on install
'Manifest 2' or something?

v.1.0.1 from Play store loads OK.
 
_chrome://about_
Does nothing

_kiwi://about_
Errors
_about:blank#blocked_

Maybe just needs more Permissions?

> _Replace the page that you see when opening a new tab_
> _Read and change your bookmarks_

I'm not worried ...
Eric

**Comment by d3ward** [comment]
I fixed the schema links with the new v2.0.0. Now you can add kiwi:// or chrome://. 
Although with the web version these links may not work properly, I will soon update the extension version where this type of links works better.
