### ISSUE TITLE
Override old new tab link.

### ISSUE THREAD

**Issue by kyoyacchi** [d3ward/nextntp#28]
Hi. It's not working in group tabs. So i tried something to override it but didn't work. Can you help me?
That's what i tried.
![Screenshot_20221005-201226](https://user-images.githubusercontent.com/63583961/194121049-d2e2f469-e484-4bef-9492-702458ee896f.jpg)

I opened a issue about this on kiwi browser's repo, no one cared.
https://github.com/kiwibrowser/src.next/issues/547

**Comment by d3ward** [comment]
`chrome://newtab` works fine with latest Kiwi
