### ISSUE TITLE
SVG hassle when adding a custom search engine

### ISSUE THREAD

**Issue by mozomoid** [d3ward/nextntp#31]
Hi there

I simply wanted to add my native language version of Wikipedia as a custom search engine.
Wow man! What a journey

![1](https://user-images.githubusercontent.com/37461926/211761207-54381b78-c37e-41c6-9bf3-cf16f0eb0ba9.jpg)
okay

![2](https://user-images.githubusercontent.com/37461926/211761279-3b5b451c-4e1c-4d8d-b572-b0dcfa90f4ac.jpg)
ok, fairly easy to figure out on a per site basis.

![3](https://user-images.githubusercontent.com/37461926/211761301-be964869-3901-49ce-88a5-5ec82a9ecc74.jpg)
er... ah right, BG = BackGround. Do we need that? Seems redundant with the search field background color set in the Widgets section but okay, let's copy-paste the exact same color.

![4](https://user-images.githubusercontent.com/37461926/211761311-f689d72c-6583-45fe-b62a-bda10bd72163.jpg)
wtf???

How many lines of code are we supposed to put in this mandatory field?
As an average user with no advanced knowledge, I had to crawl the Internet to read up on this svg thing, then after some failing around (you cannot edit, must redo from the start) but valiant efforts of understanding, I finally came up with this:

```
<svg width="32" height="32">       
<image xlink:href="https://fr.wikipedia.org/static/favicon/wikipedia.ico" width="32" height="32"/>    
</svg>
```

which gave me that:

![5](https://user-images.githubusercontent.com/37461926/211761413-b55b50be-4e64-4ccd-aaaf-57812bc45be4.jpg)

That will do the trick. I won't go any further. </exhausted breathing>

**Adding a custom search engine should not be such a hassle for a non savy user.**

**Expected behavior:**
- Just select a local png/ico/svg or enter an URL and voilà!

One last note: I could not delete my pathetic attempts even if I wanted to, the trash icon being unresponsive:

![6b](https://user-images.githubusercontent.com/37461926/211761571-ea3ffe5f-e568-4f4a-ae4c-ffb0fe1da30c.jpg)

Thanks for considering.
And anyway, kuddos for this overall tasty piece of software ^^

**Comment by d3ward** [comment]
I updated NextNTP to v2.0.0 where it now include a better way of adding custom engine , upload form file or link included.
