### ISSUE TITLE
add "custom search engines" option

### ISSUE THREAD

**Issue by kingofcube** [d3ward/nextntp#35]
would been nice if we can change the search engine to a custom one that the extension doesn't have implemented yet :3

**Comment by d3ward** [comment]
Go to Settings> Search Bar and at the bottom you can add a custom search

**Comment by thebisexual** [comment]
> Go to Settings> Search Bar and at the bottom you can add a custom search Ps. For icons SVG i recommend checking https://simpleicons.org if available , copy & paste the logo in the SVG input

ok thanks
