### ISSUE TITLE
Added custom engines not working on v2.0.0

### ISSUE THREAD

**Issue by mozomoid** [d3ward/nextntp#39]
Hi d3ward

First of all, thanks for implementing a better way of adding custom engines in v2.0.0.

Problem is that once added, the custom engines don't work:

- Type something in search field.
- Tap [Enter] on keyboard.
- Nothing happens.

Here are exemples of additions in the "Search Query" field:

https://fr.m.wikipedia.org/w/index.php?search=
https://www.ebay.fr/sch/i.html?_nkw=

which work fine with v1.0.4

Tested on a fresh v2.0.0 install from .crx on Kiwi Browser 124.0.6327.1 from Google Play, with all other extensions disabled.
Even tried the 3 ways of adding an icon (svg code, from link, from file) just in case.
Whatever the keyboard used (Gboard, OpenBoard, Floris...), taping [Enter] has no effect with added custom engines.

So back to v1.0.4 for now.

**Comment by d3ward** [comment]
This should now be fixed with 2.0.1, if not please feel free to reopen the issue.
